#define T_PROGRAM       1  
#define T_FUNCTION      2   
#define T_ENDFUNCTION   3
#define T_VARS          4  
#define T_CHAR          5 
#define T_INT           6
#define T_RETURN        7
#define T_STARTMAIN     8
#define T_ENDMAIN       9
/*Εντολές*/ 
#define T_WHILE         10
#define T_ENDWHILE      11
#define T_FOR           12
#define T_TO            13
#define T_STEP          14
#define T_ENDFOR        15
#define T_IF            16
#define T_THEN          17
#define T_ELSE          18
#define T_ELSEIF        19
#define T_ENDIF         20
#define T_SWITCH        21
#define T_CASE          22
#define T_DEFAULT       23
#define T_ENDSWITCH     24
#define T_PRINT         25
#define T_BREAK         26
/*Symbols*/
#define T_ADD           27
#define T_SUB           28        
#define T_POWER         29
#define T_MUL           30
#define T_DIV           31
#define T_LT            32
#define T_GT            33
#define T_EQ            34
#define T_NQ            35
#define T_AND           36
#define T_OR            37
#define T_ASSIGN        38
#define T_LPAR          39     
#define T_RPAR          40
#define T_SCOLON        41
#define T_COMMA         42               
#define T_COLON         43       
#define T_LBRAC         44
#define T_RBRAC         45
#define T_NL            47
#define Unknown         48
#define T_ID            49
#define T_NUMBER        50
#define T_C             51
/*End of File*/
#define T_EOF           0